server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://ms-auth-db:3306/authDBnew?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
security:
  oauth2:
    resource:
      token-info-uri: http://ms-auth-con:9191/oauth/check_token
    client:
      client-id: MovieScraper
      client-secret: pin
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery-con:8761/eureka