version: '3'
services:
  ms-auth-db:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=authDBnew
    ports:
      - "3307:3306"
    volumes:
      - /mnt/e/MovieScraper/db/auth:/tmp/database
    command: mysqld --init-file="/tmp/database/install_db.sql"
  ms-user-db:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=moviescraperuser
    ports:
      - "3308:3306"
  ms-gateway-con:
    image: ms-gateway-img
    ports:
      - "8990:8990"
    build:
      context: "/mnt/e/MovieScraper/api-gateway-zuul"
      dockerfile: "Dockerfile"
  ms-discovery-con:
    image: ms-discovery-img
    ports:
      - "8761:8761"
    build:
      context: "/mnt/e/MovieScraper/discovery-service"
      dockerfile: "Dockerfile"
  ms-auth-con:
    image: ms-auth-img
    ports:
      - "9191:9191"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ms-auth-db:3306/authDBnew?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    build:
      context: "/mnt/e/MovieScraper/authorization-server-new"
      dockerfile: "Dockerfile"
    depends_on:
      - ms-auth-db
  ms-user-con:
    image: ms-user-img
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ms-user-db:3306/moviescraperuser?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    build:
      context: "/mnt/e/MovieScraper/user-service"
      dockerfile: "Dockerfile"
    depends_on:
      - ms-user-db