spring:
  datasource:
    url: jdbc:mysql://ms-user-db:3306/moviescraperuser?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    discovery:
      enabled: true
security:
  oauth2:
    resource:
      token-info-uri: http://ms-auth-con:9191/oauth/check_token
    client:
      client-id: MovieScraper
      client-secret: pin
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery-con:8761/eureka
